services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  app:
    container_name: jakdojade
    build: Dockerfile

volumes:
  pgdata:
