"""add_composite_index

Revision ID: 508cf70e49f2
Revises: bbd4b6d8bcf8
Create Date: 2022-12-07 11:18:05.486389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508cf70e49f2'
down_revision = 'bbd4b6d8bcf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bus_stops_stop_id', table_name='bus_stops')
    op.create_index('ix_stop_id', 'bus_stops', ['stop_id'], unique=False)
    op.drop_index('ix_tables_bus_stop', table_name='tables')
    op.create_index('ix_bus_stop_and_time', 'tables', ['bus_stop', 'time'], unique=False)
    op.create_index('ix_search_course', 'tables', ['line', 'brigade', 'direction', 'route', 'time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_course', table_name='tables')
    op.drop_index('ix_bus_stop_and_time', table_name='tables')
    op.create_index('ix_tables_bus_stop', 'tables', ['bus_stop'], unique=False)
    op.drop_index('ix_stop_id', table_name='bus_stops')
    op.create_index('ix_bus_stops_stop_id', 'bus_stops', ['stop_id'], unique=False)
    # ### end Alembic commands ###
